### ISSUE TITLE
set frequency

### ISSUE THREAD

**Issue by winefnoob** [gordonthree/pca9633#10]
Hello 
first : thanks for the lib  ! 
second : I'm very new to github, I really don't know if it's the correct way to ask you this ...

Is it possible to set the frequency of the pwm output of the pca9633 ?
I see a : "   #define GRPFREQ			(0x07) // group frequency    " in 9633.h  but no mentions of it else where.

I'm trying to control a CN5711 led driver and it works with pwm directly from the esp32 at 1khz but not with the pca (1.6khz)

**Comment by gordonthree** [comment]
You're better off with the ESP32, its pwm is quite flexible, and it has a lot of other options. 

For the 9633 the groupfreq setting controls blinking on a group of outputs. The PWM frequency is fixed at 97khz for individual outputs, and there is also a fixed 190hz group dimming frequency. See page 4 of the NXP datasheet.

Closed - not possible with this chip.

**Comment by gordonthree** [comment]
not possible with this chip.

**Comment by winefnoob** [comment]
thanks for the quick reply !
I'm used to the PCA9685 who is ajustable in frequency but unfortunately to big and to expensive for my pcb design. 

I've digged further more the datasheet with attention to your remarks
and from my understanding the PCA9632 could actualy work with the CN5711 since individual pwm is set at 1.5625 kHz
but looks like the hardest part is to get my hands on one !!!

Anyway thanks again for the lib and quick reply

**Comment by winefnoob** [comment]
hello me again !

I've got a pca9632 and it outputs pwm but at 6.8Khz !!!
I gess my oscilloscope or my wiring is not perfect and the true value is the 6.25 kHz specified in the datasheet.

So I'm still tring to get 1.5625 kHz out of the pca9632
I've tried switching from  these command lines
rgbw.setrgbw(128,128,128,128); 
rgbw.setpwm(0,128);

hoping to switch  from "group dimming mode"  (6.25 kHz PWM )
to "Individual brightness mode" ( 1.5625 kHz PWM )
but it stills outputs at 6.2khz

I don't understand is there a way to get a 1.5kHz signal out of the 9632 ?

best regards

**Comment by winefnoob** [comment]
found it !

Wire.beginTransmission(0x62); // talk to pca9632
Wire.write(0x08); // select ledout registery
Wire.write(0x02); // put it in individual mode
Wire.endTransmission(); // end essage
