### ISSUE TITLE
Publish the library

### ISSUE THREAD

**Issue by red-scorp** [gordonthree/pca9633#6]
Hi!

Will you publish the library?
HowTos:
- Platformio: https://docs.platformio.org/en/latest/userguide/lib/cmd_register.html#cmd-lib-register
- Arduino: https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-publish-a-new-release-once-my-library-is-in-the-list

Or should I do it?

Have fun! WBR,
Ag

**Comment by gordonthree** [comment]
Thanks for the help and prodding to move this library forward :)

I've submitted to Platformio and Arduino

**Comment by red-scorp** [comment]
No prob! 😀👍
WBR, Ag
