### ISSUE TITLE
Schematic and experience

### ISSUE THREAD

**Issue by maxholgasson** [gordonthree/pca9633#9]
HI,
really nice project!
do you have the schematic and would share it for your driver? What was your experience with EMI driving directly the mosfet?

**Comment by gordonthree** [comment]
Check out this project, it is very similar, I basically added the LED drivers in between the ESP and the mosfet driver. https://github.com/gordonthree/espSwitch

I don't recall any EMI trouble. I have a few of these around the house running single color or dual white led strips.  You can see on my PCB layout extensive use of ground plane pours, I like to go overkill on that.

I eventually moved on to using the PCA9685 for more channels, and a bigger board that would accept a Wemos D1 mini.
